In [1]:
import pandas as pd
import numpy as np
import sklearn
import scipy
from sklearn.feature_extraction.text import CountVectorizer

In [90]:
data = pd.read_csv('accounts_payable_atcat.csv')

In [91]:
data_cut = data[['InvoiceNumber', 'InvoiceDate', 'InvoiceTotal', 'VendorName']]

In [92]:
data_cut.head()

InvoiceNumber InvoiceDate InvoiceTotal VendorName
0          1234   9/15/2012     $300.00         NaN
1          12&3    9/8/2012       $0.00         NaN
2          1234   9/15/2012     $300.00         NaN
3         1234A   9/15/2012    ($250.00)        NaN
4          8888   9/25/2012   $3,500.00         NaN

In [93]:
data_cut.VendorName[data_cut.VendorName.isnull()] = 'no_name'

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5233: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2862: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)


In [94]:
dummy_data = pd.get_dummies(data_cut, columns=list(data_cut.columns))

In [95]:
dummy_data.head()

InvoiceNumber_  1  InvoiceNumber_  55  InvoiceNumber_-77711  \
0                  0                   0                     0   
1                  0                   0                     0   
2                  0                   0                     0   
3                  0                   0                     0   
4                  0                   0                     0   

   InvoiceNumber_0000000050  InvoiceNumber_00002357  InvoiceNumber_00002366  \
0                         0                       0                       0   
1                         0                       0                       0   
2                         0                       0                       0   
3                         0                       0                       0   
4                         0                       0                       0   

   InvoiceNumber_00002367  InvoiceNumber_00002369  InvoiceNumber_0005371  \
0                       0                       0                      0   
1                       0                       0                      0   
2                       0                       0                      0   
3                       0                       0                      0   
4                       0                       0                      0   

   InvoiceNumber_0008888         ...          VendorName_One  \
0                      0         ...                       0   
1                      0         ...                       0   
2                      0         ...                       0   
3                      0         ...                       0   
4                      0         ...                       0   

   VendorName_One inc  VendorName_Seven  VendorName_Seven inc  \
0                   0                 0                     0   
1                   0                 0                     0   
2                   0                 0                     0   
3                   0                 0                     0   
4                   0                 0                     0   

   VendorName_Ten inc  VendorName_Three  VendorName_Two  VendorName_Two inc  \
0                   0                 0               0                   0   
1                   0                 0               0                   0   
2                   0                 0               0                   0   
3                   0                 0               0                   0   
4                   0                 0               0                   0   

   VendorName_William Rigg  VendorName_no_name  
0                        0                   1  
1                        0                   1  
2                        0                   1  
3                        0                   1  
4                        0                   1  

[5 rows x 974 columns]

In [102]:
vocab = set().union(data_cut.InvoiceNumber, data_cut.InvoiceDate, data_cut.InvoiceTotal, data_cut.VendorName)   # set(data_cut.InvoiceDate) + set(data_cut.InvoiceDate) + set(data_cut.VendorName)

In [124]:
vocab_vectorizer = CountVectorizer(vocabulary=vocab)
csr_vec_vocab = vocab_vectorizer.fit_transform(data_cut.joined)

In [125]:
model_vocab = NearestNeighbors(2, metric='jaccard')
trained_model_vocab = model_vocab.fit(csr_vec_vocab.toarray())

In [30]:
len(dummy_data.columns)

974

In [106]:
data_lis = data_cut.apply(lambda row:' '.join([str(i) for i in row]), axis=1)

In [36]:
dat_lissd

NameError: name 'dat_lissd' is not defined

In [107]:
data_cut['joined'] = data_lis

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [38]:
data_cut['split'] = data_cut.joined.apply(lambda string_: string_.split())

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [39]:
data_cut.head()

InvoiceNumber InvoiceDate InvoiceTotal VendorName  \
0          1234   9/15/2012     $300.00     no_name   
1          12&3    9/8/2012       $0.00     no_name   
2          1234   9/15/2012     $300.00     no_name   
3         1234A   9/15/2012    ($250.00)    no_name   
4          8888   9/25/2012   $3,500.00     no_name   

                              joined                                   split  
0    1234 9/15/2012 $300.00  no_name     [1234, 9/15/2012, $300.00, no_name]  
1       12&3 9/8/2012 $0.00  no_name        [12&3, 9/8/2012, $0.00, no_name]  
2    1234 9/15/2012 $300.00  no_name     [1234, 9/15/2012, $300.00, no_name]  
3  1234A 9/15/2012 ($250.00) no_name  [1234A, 9/15/2012, ($250.00), no_name]  
4  8888 9/25/2012 $3,500.00  no_name   [8888, 9/25/2012, $3,500.00, no_name]

In [118]:
vectorizer = CountVectorizer()
csr_vec = vectorizer.fit_transform(data_cut.joined)

In [41]:
csr_vec

<940x801 sparse matrix of type '<class 'numpy.int64'>'
	with 6157 stored elements in Compressed Sparse Row format>

In [42]:
from sklearn.neighbors import NearestNeighbors

In [43]:
model = NearestNeighbors(2, metric='jaccard')
trained_model = model.fit(csr_vec.toarray())

In [126]:
test_val = vectorizer.transform([data_cut.joined[1]])
# test_val = vectorizer.transform(['## ^^ &&'])

In [127]:
test_val_vocab = vocab_vectorizer.transform([data_cut.joined[1]])

In [60]:
trained_model.kneighbors(test_val.toarray(),3,return_distance=True)

(array([[ 0.  ,  0.  ,  0.25]]), array([[365,   1, 381]], dtype=int64))

In [128]:
trained_model_vocab.kneighbors(test_val_vocab.toarray(),3,return_distance=True)

(array([[ 0.,  0.,  0.]]), array([[409, 365, 397]], dtype=int64))

In [130]:
data_cut.joined[397]

'2468EFCD 12/1/2012 $2,900.00  no_name'

In [55]:
features = vectorizer.get_feature_names()

In [61]:
data_cut.joined[365]

'12&3 9/8/2012 $0.00  no_name'

In [67]:
data_cut.ix[381]

InvoiceNumber                                1
InvoiceDate                           6/8/2012
InvoiceTotal                            $0.00 
VendorName                             no_name
joined               1 6/8/2012 $0.00  no_name
split            [1, 6/8/2012, $0.00, no_name]
Name: 381, dtype: object

In [71]:
from scipy.spatial.distance import jaccard

u = [1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
v = [0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
jaccard(u,v)

0.66666666666666663

In [74]:
u = csr_vec.toarray()[1]
v = csr_vec.toarray()[365]
w = csr_vec.toarray()[381]

In [81]:
feature_array = np.array(features)

In [89]:
feature_array[w == 1]

array(['00', '2012', 'no_name'],
      dtype='<U16')

In [1]:
import numpy as np
from sklearn.neighbors import NearestNeighbors

In [12]:
neigh = NearestNeighbors(2, metric='jaccard')
samples = [[0, 0, 2], [1, 0, 0], [0, 0, 500]]

In [13]:
neigh.fit(samples)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='jaccard',
         metric_params=None, n_jobs=1, n_neighbors=2, p=2, radius=1.0)

In [14]:
neigh.kneighbors([[1, 0, 10]], 2, return_distance=True)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to bool by check_pairwise_arrays.
  warnings.warn(msg, DataConversionWarning)


(array([[ 0.5,  0.5]]), array([[0, 1]], dtype=int64))